Hw03 mongodb
vpoklad/nodejs-homework pull request #2
Opened 2021-12-26 14:41 UTC by vpoklad

2021-12-26 15:33 UTC, KirillKulakow commented on .vscode/launch.json
> +{
зачем этот файл в гите?

2021-12-26 15:35 UTC, KirillKulakow commented on controllers/contacts/index.js
> +    .json({ status: 'success', code: HttpCode.OK, data: { ...contacts } });
зачем данная строка?` data: { ...contacts }`

2021-12-26 15:35 UTC, KirillKulakow requested changes
Need fix

2021-12-26 17:37 UTC, vpoklad commented on controllers/contacts/index.js
> +    .json({ status: 'success', code: HttpCode.OK, data: { ...contacts } });
исправил. теперь data это массив документов (контактов).

2021-12-26 17:38 UTC, vpoklad commented on .vscode/launch.json
> +{
добавил в gitignore

2021-12-29 17:33 UTC, KirillKulakow approved these changes

2021-12-29 17:39 UTC, merged